/*
 * Calculation API
 *
 * Calculation API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CalculateBody : IEquatable<CalculateBody>
    { 
        /// <summary>
        /// Gets or Sets Operand1
        /// </summary>

        [DataMember(Name="Operand1")]
        public decimal? Operand1 { get; set; }

        /// <summary>
        /// Gets or Sets Operand2
        /// </summary>

        [DataMember(Name="Operand2")]
        public decimal? Operand2 { get; set; }

        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OperationEnum
        {
            /// <summary>
            /// Enum AddEnum for add
            /// </summary>
            [EnumMember(Value = "add")]
            AddEnum = 0,
            /// <summary>
            /// Enum SubtractEnum for subtract
            /// </summary>
            [EnumMember(Value = "subtract")]
            SubtractEnum = 1,
            /// <summary>
            /// Enum MultiplyEnum for multiply
            /// </summary>
            [EnumMember(Value = "multiply")]
            MultiplyEnum = 2,
            /// <summary>
            /// Enum DivideEnum for divide
            /// </summary>
            [EnumMember(Value = "divide")]
            DivideEnum = 3        }

        /// <summary>
        /// Gets or Sets Operation
        /// </summary>

        [DataMember(Name="operation")]
        public OperationEnum? Operation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CalculateBody {\n");
            sb.Append("  Operand1: ").Append(Operand1).Append("\n");
            sb.Append("  Operand2: ").Append(Operand2).Append("\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CalculateBody)obj);
        }

        /// <summary>
        /// Returns true if CalculateBody instances are equal
        /// </summary>
        /// <param name="other">Instance of CalculateBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CalculateBody other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Operand1 == other.Operand1 ||
                    Operand1 != null &&
                    Operand1.Equals(other.Operand1)
                ) && 
                (
                    Operand2 == other.Operand2 ||
                    Operand2 != null &&
                    Operand2.Equals(other.Operand2)
                ) && 
                (
                    Operation == other.Operation ||
                    Operation != null &&
                    Operation.Equals(other.Operation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Operand1 != null)
                    hashCode = hashCode * 59 + Operand1.GetHashCode();
                    if (Operand2 != null)
                    hashCode = hashCode * 59 + Operand2.GetHashCode();
                    if (Operation != null)
                    hashCode = hashCode * 59 + Operation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CalculateBody left, CalculateBody right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CalculateBody left, CalculateBody right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
